### ISSUE TITLE
[Question] gfal-copy failed with Segmentation fault

### ISSUE THREAD

**Issue by a6350202** [cern-fts/homebrew-dmc#4] opened 2018-03-09 09:44 UTC
Hello again, 
due to this question is not related to my pervious one, I create a new issue.

I need to use gfal2 to run Rucio command (download/upload), 
but after running to [this line](https://gitlab.cern.ch/plove/rucio/blob/master/lib/rucio/rse/protocols/gfal.py#L328) leads to **Segmentation fault: 11**.
```
> /opt/rucio/lib/rucio/rse/protocols/gfal.py(369)__gfal2_copy()
-> ret = ctx.filecopy(params, str(src), str(dest))
(Pdb)
Segmentation fault: 11
```

So I try to initial a virtualenv (follow README of this project), 
and run gfal-copy command also get error: **Segmentation fault: 11**. 
```
(.venv) Mandyde-MacBook-Pro:rucio root# gfal-copy README.rst xroot://<our_storage>//eos/tmp/README.rst
180309 17:23:21 9735 secgsi_InitProxy: cannot access private key file: /var/root/.globus/userkey.pem
Segmentation fault: 11
```

My MacBook OS version: 10.12.6
Python version: 2.7.10

**Comment by andrea-manzi** [comment] 2018-03-12 10:51
Hi,
from the logs looks like you cannot access the local certificate.
do you have one and with the correct permission?
thanks
Andrea

**Comment by a6350202** [comment] 2018-03-13 04:28
Yes, I have one. 
But there is no permission on my certificate to access storage. 
I try to copy our root proxy as `/tmp/x509up_u0` and execute gfal-copy again.

The error of `secgsi_InitProxy: cannot access private key file: /var/root/.globus/userkey.pem` didn't occur. 
and it still show **Segmentation fault: 11**:
```
(.venv) Mandyde-MacBook-Pro:dicos-rucio root# gfal-copy README.rst xroot://<our_storage>//eos/tmp/README.rst
Segmentation fault: 11
```

**Comment by andrea-manzi** [comment] 2018-03-13 09:10
are you running as root? cause otherwise the proxy should be the one of the user ( /tmp/x509up_u<user id>

you should also use the file:/// protocol if you want to copy from local file:

gfal-copy file:///README.rst xroot://<our_storage>//eos/tmp/README.rst

**Comment by a6350202** [comment] 2018-03-19 09:48
Sorry for the late reply...
Yes, I am running as root and the proxy file name is also right...

I try your command `gfal-copy file:///opt/dicos-rucio/README.rst xroot://<our_storage>//eos/tmp/README.rst` 

still shows `Segmentation fault: 11`

**Comment by andrea-manzi** [comment] 2018-03-19 11:45
sorry i was not able to test it so far as my Mac was being repaired.
i have the same problem on gfal-copy, ( other commands are working though)
i'm going to investigate

**Comment by chrisburr** [comment] 2019-06-18 15:55
This should be fixed now: https://its.cern.ch/jira/browse/DMC-1026

**Comment by andrea-manzi** [comment] 2019-06-20 11:49
i can confirm that the segmentation fault is gone, thanks @chrisburr for the fix

**Closed as completed by andrea-manzi** 2019-06-20 11:49 UTC
Labels: bug
